site_name: openyieldtables
site_description: An open source library for yield tables

theme:
  name: readthedocs

repo_name: openyieldtables
repo_url: https://github.com/treely/openyieldtables
edit_uri: edit/main/docs/

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Overview: index.md
  - Data model: data_model.md
  - Functions: functions.md
  - Contributing: contributing.md
  - About: about.md

plugins:
  - search
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_root_full_path: false

extra:
  yield_tables_meta:
    id: The unique identifier of the yield table.
    title: The name/title of the yield table.
    country_codes: The ISO 3166-1 alpha-2 country codes of the countries the yield table is applicable to.
    type: The type of the yield table (e.g. `dgz_100`).
    source: The source of the yield table.
    link: A link to the source of the yield table or the yield table itself.
    yield_class_step: The step between the yield classes.
    age_step: The step between the ages.
    tree_type: "The tree type: `coniferous` or `deciduous`."
  yield_tables:
    id: The unique identifier of the yield table.
    yield_class: The yield class.
    age: The age in years.
    dominant_height: The dominant height in m.
    average_height: The average height in m.
    dbh: The diameter at breast height in cm.
    taper: The tree taper.
    trees_per_ha: The number of trees per hectare.
    basal_area: The basal area in m2.
    volume_per_ha: The volume per hectare in vfm.
    average_annual_age_increment: The average annual increment up to a certain age in volume per hectare vfm.
    total_growth_performance: The total growth performance in volume per hectare vfm.
    current_annual_increment: The current annual increment in volume per hectare vfm.
    mean_annual_increment: The mean annual increment in volume per hectare vfm.
