---
name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.8.2
      # set-up python with cache
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      # install requirements
      - name: Install requirements
        run: poetry install
      # run linters
      - name: Run linters
        run: |
          set -o pipefail
          poetry run pre-commit run --all-files
      # run unit tests
      - name: Run tests
        run: |
          set -o pipefail
          poetry run pytest -- --cov-report xml
      # add pytest coverage report to PR
      - name: Pytest coverage comment
        if: ${{ success() && github.event_name == 'pull_request' }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          title: Coverage Report
          pytest-xml-coverage-path: coverage.xml
